### ISSUE TITLE
Pack client running as Tekton's task should access a docker daemon to build the builder image

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/ubi-image-builder#3]
## Issue

The pack client should access a docker daemon to build the builder image otherwise you will get this error running the tekton pack client task
```

pack builder create quay.io/swowdrop/ubi-builder --config ubi-builder.toml
[pack : pack] Pulling image 'index.docker.io/paketocommunity/run-ubi-base:latest'
[pack : pack] ERROR: invalid run image config: failed to fetch image: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by matejvasek** [comment]
Have you tried `--publish` flag?

**Comment by matejvasek** [comment]
or packdocker https://github.com/matejvasek/packdocker

**Comment by cmoulliard** [comment]
> Have you tried `--publish` flag?

This parmater will be used after the image has been build using a docker daemon !

**Comment by cmoulliard** [comment]
> or packdocker https://github.com/matejvasek/packdocker

Is packdocker available as container image ? @matejvasek

**Comment by cmoulliard** [comment]
> The pack client should access a docker daemon to build the builder image otherwise you will get this error running the tekton pack client task

A solution is to use kubevirt to run a Feodra + Podman VM as we did for this project: https://github.com/iocanel/openshift-vm-playground

**Comment by BarDweller** [comment]
> > Have you tried `--publish` flag?
> 
> This parmater will be used after the image has been build using a docker daemon !

--publish will allow the build to occur without a docker daemon, it's sort of how they split their stuff, either it's going to a local daemon, or it's using a remote registry.. by setting --publish it allows the build to occur against the remote registry.. 

```
$ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
$ pack builder create 192.168.1.155:5000/ozzy/testbuilder --publish --config builder.toml 
Successfully created builder image 192.168.1.155:5000/ozzy/testbuilder
Tip: Run pack build <image-name> --builder 192.168.1.155:5000/ozzy/testbuilder to use this builder
```
(I'm running a local registry on my lan at 192.168.1.155:5000 ... add --verbose if you want to see it do the build)

**Comment by matejvasek** [comment]
> it's sort of how they split their stuff, either it's going to a local daemon, or it's using a remote registry.. by setting --publish it allows the build to occur against the remote registry..

At the end you can push the tarballs using `carane` or `sokpeo`. (or maybe all push endpoint)

**Comment by matejvasek** [comment]
> > Have you tried `--publish` flag?
> 
> This parmater will be used after the image has been build using a docker daemon !

I do not follow.

**Comment by cmoulliard** [comment]
> At the end you can push the tarballs using `carane` or `sokpeo`. (or maybe call push endpoint)

Do you have an example using skopeo ?

**Comment by cmoulliard** [comment]
That works using `--publish`
